[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "overcooked"
version = "1.0.0"
description = "Overcooked-AI environment with multi-agent convergence speed research framework"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [{ name = "Shixian Li" }]
urls = { homepage = "https://github.com/zxlishixian/overcooked" }
keywords = ["Overcooked", "MARL", "Reinforcement Learning", "Convergence", "Specialization"]
dependencies = [
    "dill",
    "gymnasium",
    "numpy<2",
    "opencv-python",
    "pygame",
    "scipy",
    "tqdm",
    "torch>=1.10.0",
    "matplotlib",
]

[tool.setuptools.package-data]
"overcooked_ai_py" = [
    "data/layouts/*.layout",
    "data/planners/*.py",
    "data/graphics/*.png",
    "data/graphics/*.json",
    "data/fonts/*.ttf",
]
